import Head from 'next/head'
import { orbitClient } from 'lib'
import { useEffect } from 'react'
import ColumnsContainer from 'components/ColumnsContainer'

export default function Home() {
  useEffect(() => {
    if (typeof window !== 'undefined') {
      // orbitClient()
      console.log('run')
    }
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-medium">Orbitretro</h1>

      <ColumnsContainer />
    </>
  )
}
